### ISSUE TITLE
VR - push-pull models (sec 3cII+3cIII)

### ISSUE THREAD

**Issue by tussbaum** [GalaxyHunters/Vivid_VR#19]
DOD - כאשר מצביעים על מודל בלבד!
על מודל: אצבע מורה + גויסטיק קדימה -> מרחיק מודל
על מודל: אצבע מורה + ג'ויסטיק אחורה -> מקרב מודל

**Comment by lenechk** [comment]
done and added an option to drag the model around from afar

**Comment by lenechk** [comment]
an error might occur if we pull 2 objects at once, one wont release, will fix tomorrow
